# Generated by Django 4.2.1 on 2023-05-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommitteemember',
            name='exam_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee_for_members', to='core.examcommittee'),
        ),
        migrations.AlterField(
            model_name='tabulator',
            name='exam_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_committee', to='core.examcommittee'),
        ),
    ]
