# Generated by Django 4.2.1 on 2023-05-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labcourse')),
            ],
        ),
        migrations.CreateModel(
            name='LabExamInvigilator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='core.labcourseschedule')),
            ],
        ),
        migrations.AddField(
            model_name='labcourseschedule',
            name='invigilator',
            field=models.ManyToManyField(related_name='lab_course_invigilator', through='core.LabExamInvigilator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labcourseschedule',
            name='lab_exam_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labexaminvigilationschedule'),
        ),
        migrations.AddField(
            model_name='labexaminvigilationschedule',
            name='lab_course_schedule',
            field=models.ManyToManyField(through='core.LabCourseSchedule', to='core.labcourse'),
        ),
    ]
