# Generated by Django 4.1.7 on 2023-04-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.CreateModel(
            name='LabCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.course')),
                ('credit', models.IntegerField()),
            ],
            bases=('core.course',),
        ),
        migrations.AlterField(
            model_name='examresponsibility',
            name='course_lab_tutorial',
            field=models.ManyToManyField(to='core.labcourse'),
        ),
    ]
