# Generated by Django 4.2.1 on 2023-05-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notice_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticequestionmoderation',
            name='external_examiner',
        ),
    ]
