# Generated by Django 4.2.1 on 2023-05-23 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_examresponsibility_course_lab_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabulatorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinee_no', models.IntegerField()),
                ('tabulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulator_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabulatorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examcommittee')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('tabulators', models.ManyToManyField(related_name='tabulator_list', through='core.TabulatorInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tabulatorinfo',
            name='tabulator_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabulatorlist'),
        ),
    ]
