# Generated by Django 4.2.1 on 2023-05-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tabulatorinfo_tabulatorlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresponsibility',
            name='tabulators',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulator_list', to='core.tabulatorlist'),
        ),
    ]
