# Generated by Django 4.1.7 on 2023-04-28 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examcommitte', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examcommittee',
            name='chairman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='exam_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examsystem', to_field='year'),
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='member_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examcommittee',
            name='member_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examcommittee',
            unique_together={('chairman', 'member_1', 'member_2', 'exam_year')},
        ),
    ]
