# Generated by Django 4.1.7 on 2023-04-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('examcommitte', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examcommittee',
            unique_together={('exam_system', 'exam_year')},
        ),
    ]
