# Generated by Django 4.1.7 on 2023-04-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examcommitte', '0003_alter_examcommittee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcommittee',
            name='chairman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examcommittee',
            name='member_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examcommittee',
            name='member_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
