# Generated by Django 4.2.1 on 2023-05-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
    ]
