# Generated by Django 4.1.7 on 2023-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_department_chairman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('department', 'is_department_chairman')},
        ),
    ]
